# Generated by Django 4.0.4 on 2022-07-04 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='MyUser',
        ),
    ]
